# Generated by Django 4.2.25 on 2025-10-21 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Diagnóstico",
                "verbose_name_plural": "Diagnósticos",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("es_final", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Etapa",
                "verbose_name_plural": "Etapas",
                "ordering": ("orden", "nombre"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resultado",
                "verbose_name_plural": "Resultados",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sindicato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sindicato",
                "verbose_name_plural": "Sindicatos",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subsistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subsistema",
                "verbose_name_plural": "Subsistemas",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoTramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Trámite",
                "verbose_name_plural": "Tipos de Trámite",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(blank=True, max_length=25, unique=True)),
                (
                    "tramite_inicial_o_prorroga",
                    models.CharField(
                        choices=[
                            ("inicial", "Trámite inicial"),
                            ("prorroga", "Prórroga"),
                            ("otro", "Otro / No especificado"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("trabajador_nombre", models.CharField(max_length=255)),
                ("contacto", models.TextField(blank=True)),
                ("oficio_origen_num", models.CharField(blank=True, max_length=100)),
                ("fecha_recepcion_nivel", models.DateField(blank=True, null=True)),
                ("incidencias_integracion", models.TextField(blank=True)),
                (
                    "oficio_envio_subsecretaria",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "fecha_recepcion_subsecretaria",
                    models.DateField(blank=True, null=True),
                ),
                ("incidencias_vobo", models.TextField(blank=True)),
                ("vobo_num_y_fecha", models.CharField(blank=True, max_length=150)),
                ("oficio_envio_rh", models.CharField(blank=True, max_length=100)),
                ("fecha_recepcion_rh", models.DateField(blank=True, null=True)),
                (
                    "oficio_resolucion_num_y_fecha",
                    models.CharField(blank=True, max_length=150),
                ),
                ("persona_tramita", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tramites",
                        to="licencias.diagnostico",
                    ),
                ),
                (
                    "estado_actual",
                    models.ForeignKey(
                        help_text="Etapa actual del trámite",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramites",
                        to="licencias.etapa",
                    ),
                ),
                (
                    "resultado_resolucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tramites",
                        to="licencias.resultado",
                    ),
                ),
                (
                    "sindicato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tramites",
                        to="licencias.sindicato",
                    ),
                ),
                (
                    "subsistema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramites",
                        to="licencias.subsistema",
                    ),
                ),
                (
                    "tipo_tramite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tramites",
                        to="licencias.tipotramite",
                    ),
                ),
                (
                    "user_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tramites_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Oficio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("origen", "Oficio de origen"),
                            ("envio_subsecretaria", "Envío a Subsecretaría"),
                            ("envio_rh", "Envío a Recursos Humanos"),
                            ("vobo", "Visto Bueno"),
                            ("resolucion", "Resolución"),
                            ("notif_sindicato", "Notificación sindicato"),
                            ("notif_trabajador", "Notificación trabajador"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=25,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=150)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "area_emisora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="oficios",
                        to="licencias.area",
                    ),
                ),
                (
                    "tramite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oficios",
                        to="licencias.tramite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oficio",
                "verbose_name_plural": "Oficios",
                "ordering": ("-fecha", "tipo"),
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        choices=[
                            ("sindicato", "Sindicato"),
                            ("trabajador", "Trabajador"),
                            ("otro", "Otro"),
                        ],
                        default="sindicato",
                        max_length=20,
                    ),
                ),
                ("numero_oficio", models.CharField(blank=True, max_length=150)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "tramite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="licencias.tramite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ("-fecha", "destinatario"),
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "etapa_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_salientes",
                        to="licencias.etapa",
                    ),
                ),
                (
                    "etapa_nueva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_entrantes",
                        to="licencias.etapa",
                    ),
                ),
                (
                    "tramite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="licencias.tramite",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
                "ordering": ("-fecha",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalTramite",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("folio", models.CharField(blank=True, db_index=True, max_length=25)),
                (
                    "tramite_inicial_o_prorroga",
                    models.CharField(
                        choices=[
                            ("inicial", "Trámite inicial"),
                            ("prorroga", "Prórroga"),
                            ("otro", "Otro / No especificado"),
                        ],
                        default="otro",
                        max_length=20,
                    ),
                ),
                ("trabajador_nombre", models.CharField(max_length=255)),
                ("contacto", models.TextField(blank=True)),
                ("oficio_origen_num", models.CharField(blank=True, max_length=100)),
                ("fecha_recepcion_nivel", models.DateField(blank=True, null=True)),
                ("incidencias_integracion", models.TextField(blank=True)),
                (
                    "oficio_envio_subsecretaria",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "fecha_recepcion_subsecretaria",
                    models.DateField(blank=True, null=True),
                ),
                ("incidencias_vobo", models.TextField(blank=True)),
                ("vobo_num_y_fecha", models.CharField(blank=True, max_length=150)),
                ("oficio_envio_rh", models.CharField(blank=True, max_length=100)),
                ("fecha_recepcion_rh", models.DateField(blank=True, null=True)),
                (
                    "oficio_resolucion_num_y_fecha",
                    models.CharField(blank=True, max_length=150),
                ),
                ("persona_tramita", models.CharField(blank=True, max_length=255)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.diagnostico",
                    ),
                ),
                (
                    "estado_actual",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Etapa actual del trámite",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.etapa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resultado_resolucion",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.resultado",
                    ),
                ),
                (
                    "sindicato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.sindicato",
                    ),
                ),
                (
                    "subsistema",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.subsistema",
                    ),
                ),
                (
                    "tipo_tramite",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.tipotramite",
                    ),
                ),
                (
                    "user_responsable",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical tramite",
                "verbose_name_plural": "historical tramites",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOficio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("origen", "Oficio de origen"),
                            ("envio_subsecretaria", "Envío a Subsecretaría"),
                            ("envio_rh", "Envío a Recursos Humanos"),
                            ("vobo", "Visto Bueno"),
                            ("resolucion", "Resolución"),
                            ("notif_sindicato", "Notificación sindicato"),
                            ("notif_trabajador", "Notificación trabajador"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=25,
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=150)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "area_emisora",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.area",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tramite",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.tramite",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Oficio",
                "verbose_name_plural": "historical Oficios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNotificacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "destinatario",
                    models.CharField(
                        choices=[
                            ("sindicato", "Sindicato"),
                            ("trabajador", "Trabajador"),
                            ("otro", "Otro"),
                        ],
                        default="sindicato",
                        max_length=20,
                    ),
                ),
                ("numero_oficio", models.CharField(blank=True, max_length=150)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tramite",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.tramite",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Notificación",
                "verbose_name_plural": "historical Notificaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMovimiento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "etapa_anterior",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.etapa",
                    ),
                ),
                (
                    "etapa_nueva",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.etapa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tramite",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.tramite",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Movimiento",
                "verbose_name_plural": "historical Movimientos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="tramite",
            index=models.Index(fields=["folio"], name="licencias_t_folio_1654bc_idx"),
        ),
        migrations.AddIndex(
            model_name="tramite",
            index=models.Index(
                fields=["trabajador_nombre"], name="licencias_t_trabaja_db45a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tramite",
            index=models.Index(
                fields=["estado_actual"], name="licencias_t_estado__fb760d_idx"
            ),
        ),
    ]
