# Generated by Django 4.2.25 on 2025-10-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltramite",
            name="autorizado",
            field=models.BooleanField(default=False, verbose_name="Autorizado"),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="fecha_cita_valoracion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de la cita de valoración del trabajador (TRÁMITES ESTATALES)",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="fecha_contacto_cita",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de contacto al sindicato y al trabajador/señalar medio",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="fecha_dictamen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del dictamen"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="fecha_notificacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha en la que se realizó la notificación al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="fecha_recepcion_daf",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de recepción por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="incidencias_contacto_cita",
            field=models.TextField(
                blank=True,
                verbose_name="Incidencias en el contacto para la cita de valoración",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="oficio_dictamen_num",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Número de oficio del Dictamen emitido por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="oficio_notificacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Oficio de Notificación realizada al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="periodo_autorizado",
            field=models.CharField(blank=True, max_length=100, verbose_name="Periodo"),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_autorizado",
            field=models.BooleanField(
                default=False, verbose_name="Prórroga 1: Autorizado"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_fecha_cita",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha de la cita de valoración del trabajador (TRÁMITES ESTATALES)",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_fecha_contacto",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha en la que se contactó al sindicato y al trabajador/señalar medio",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_fecha_dictamen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Prórroga 1: Fecha del dictamen"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_fecha_ingreso",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha de ingreso al nivel educativo",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_fecha_notificacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha en la que se realizó la notificación al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_fecha_recepcion_daf",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha de recepción por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_incidencia",
            field=models.TextField(
                blank=True, verbose_name="Prórroga 1: Incidencia en la prórroga"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_oficio_dictamen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Número de oficio del Dictamen emitido por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_oficio_envio_daf",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Número de oficio de envío a la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_oficio_notificacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Oficio de Notificación de la prórroga realizada al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_oficio_origen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Número de oficio del sindicato o escrito de origen",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga1_periodo",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prórroga 1: Periodo"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_autorizado",
            field=models.BooleanField(
                default=False, verbose_name="Prórroga 2: Autorizado"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_fecha_cita",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha de la cita de valoración del trabajador (TRÁMITES ESTATALES)",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_fecha_contacto",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha en la que se contactó al sindicato y al trabajador/señalar medio",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_fecha_dictamen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Prórroga 2: Fecha del dictamen"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_fecha_ingreso",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha de ingreso al nivel educativo",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_fecha_notificacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha en la que se realizó la notificación al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_fecha_recepcion_daf",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha de recepción por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_incidencia",
            field=models.TextField(
                blank=True, verbose_name="Prórroga 2: Incidencia en la prórroga"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_oficio_dictamen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Número de oficio del Dictamen emitido por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_oficio_envio_daf",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Número de oficio de envío a la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_oficio_notificacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Oficio de Notificación de la prórroga realizada al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_oficio_origen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Número de oficio del sindicato o escrito de origen",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramite",
            name="prorroga2_periodo",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prórroga 2: Periodo"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="autorizado",
            field=models.BooleanField(default=False, verbose_name="Autorizado"),
        ),
        migrations.AddField(
            model_name="tramite",
            name="fecha_cita_valoracion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de la cita de valoración del trabajador (TRÁMITES ESTATALES)",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="fecha_contacto_cita",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de contacto al sindicato y al trabajador/señalar medio",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="fecha_dictamen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del dictamen"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="fecha_notificacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha en la que se realizó la notificación al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="fecha_recepcion_daf",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de recepción por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="incidencias_contacto_cita",
            field=models.TextField(
                blank=True,
                verbose_name="Incidencias en el contacto para la cita de valoración",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="oficio_dictamen_num",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Número de oficio del Dictamen emitido por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="oficio_notificacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Oficio de Notificación realizada al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="periodo_autorizado",
            field=models.CharField(blank=True, max_length=100, verbose_name="Periodo"),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_autorizado",
            field=models.BooleanField(
                default=False, verbose_name="Prórroga 1: Autorizado"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_fecha_cita",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha de la cita de valoración del trabajador (TRÁMITES ESTATALES)",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_fecha_contacto",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha en la que se contactó al sindicato y al trabajador/señalar medio",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_fecha_dictamen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Prórroga 1: Fecha del dictamen"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_fecha_ingreso",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha de ingreso al nivel educativo",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_fecha_notificacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha en la que se realizó la notificación al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_fecha_recepcion_daf",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 1: Fecha de recepción por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_incidencia",
            field=models.TextField(
                blank=True, verbose_name="Prórroga 1: Incidencia en la prórroga"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_oficio_dictamen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Número de oficio del Dictamen emitido por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_oficio_envio_daf",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Número de oficio de envío a la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_oficio_notificacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Oficio de Notificación de la prórroga realizada al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_oficio_origen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 1: Número de oficio del sindicato o escrito de origen",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga1_periodo",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prórroga 1: Periodo"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_autorizado",
            field=models.BooleanField(
                default=False, verbose_name="Prórroga 2: Autorizado"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_fecha_cita",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha de la cita de valoración del trabajador (TRÁMITES ESTATALES)",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_fecha_contacto",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha en la que se contactó al sindicato y al trabajador/señalar medio",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_fecha_dictamen",
            field=models.DateField(
                blank=True, null=True, verbose_name="Prórroga 2: Fecha del dictamen"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_fecha_ingreso",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha de ingreso al nivel educativo",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_fecha_notificacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha en la que se realizó la notificación al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_fecha_recepcion_daf",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Prórroga 2: Fecha de recepción por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_incidencia",
            field=models.TextField(
                blank=True, verbose_name="Prórroga 2: Incidencia en la prórroga"
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_oficio_dictamen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Número de oficio del Dictamen emitido por la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_oficio_envio_daf",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Número de oficio de envío a la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_oficio_notificacion",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Oficio de Notificación de la prórroga realizada al sindicato y al trabajador",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_oficio_origen",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Prórroga 2: Número de oficio del sindicato o escrito de origen",
            ),
        ),
        migrations.AddField(
            model_name="tramite",
            name="prorroga2_periodo",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Prórroga 2: Periodo"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="contacto",
            field=models.TextField(
                blank=True, verbose_name="Contacto del trabajador y/o sindicato"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="diagnostico",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.diagnostico",
                verbose_name="Diagnóstico",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="fecha_recepcion_nivel",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de recepción del oficio del sindicato o escrito del trabajador en el nivel educativo",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="fecha_recepcion_subsecretaria",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de recepción en la Subsecretaría/PRÓRROGAS: Fecha de recepción en la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="incidencias_integracion",
            field=models.TextField(
                blank=True,
                verbose_name="Incidencias para la integración del expediente/prevención/o contestación negativa del trámite",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="incidencias_vobo",
            field=models.TextField(
                blank=True,
                verbose_name="Incidencias para el visto bueno de la Subsecretaría",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="oficio_envio_subsecretaria",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Oficio de envío a la Subsecretaría/PRÓRROGAS Oficio de envío a la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="oficio_origen_num",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Número de oficio del sindicato o escrito de origen",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="sindicato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.sindicato",
                verbose_name="Nombre del sindicato",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="subsistema",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.subsistema",
                verbose_name="Federal/Estatal",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="tipo_tramite",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.tipotramite",
                verbose_name="Licencia o trámite",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="trabajador_nombre",
            field=models.CharField(
                max_length=255, verbose_name="Nombre del trabajador"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="tramite_inicial_o_prorroga",
            field=models.CharField(
                choices=[
                    ("inicial", "Trámite inicial"),
                    ("primera_prorroga", "Primera prórroga"),
                    ("segunda_prorroga", "Segunda prórroga"),
                    ("tercera_prorroga", "Tercera prórroga"),
                    ("cuarta_prorroga", "Cuarta prórroga"),
                    ("quinta_prorroga", "Quinta prórroga"),
                    ("sexta_prorroga", "Sexta prórroga"),
                    ("septima_prorroga", "Séptima prórroga"),
                    ("octava_prorroga", "Octava prórroga"),
                    ("otro", "Otro / No especificado"),
                ],
                default="otro",
                max_length=30,
                verbose_name="Trámite inicial o prórroga",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramite",
            name="vobo_num_y_fecha",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Número de oficio y fecha de Visto Bueno de la Subsecretaría",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="contacto",
            field=models.TextField(
                blank=True, verbose_name="Contacto del trabajador y/o sindicato"
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="diagnostico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tramites",
                to="licencias.diagnostico",
                verbose_name="Diagnóstico",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="fecha_recepcion_nivel",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de recepción del oficio del sindicato o escrito del trabajador en el nivel educativo",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="fecha_recepcion_subsecretaria",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de recepción en la Subsecretaría/PRÓRROGAS: Fecha de recepción en la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="incidencias_integracion",
            field=models.TextField(
                blank=True,
                verbose_name="Incidencias para la integración del expediente/prevención/o contestación negativa del trámite",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="incidencias_vobo",
            field=models.TextField(
                blank=True,
                verbose_name="Incidencias para el visto bueno de la Subsecretaría",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="oficio_envio_subsecretaria",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Oficio de envío a la Subsecretaría/PRÓRROGAS Oficio de envío a la Subd. de Org. y Adm. de Personal -DAF",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="oficio_origen_num",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Número de oficio del sindicato o escrito de origen",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="sindicato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tramites",
                to="licencias.sindicato",
                verbose_name="Nombre del sindicato",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="subsistema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tramites",
                to="licencias.subsistema",
                verbose_name="Federal/Estatal",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="tipo_tramite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tramites",
                to="licencias.tipotramite",
                verbose_name="Licencia o trámite",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="trabajador_nombre",
            field=models.CharField(
                max_length=255, verbose_name="Nombre del trabajador"
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="tramite_inicial_o_prorroga",
            field=models.CharField(
                choices=[
                    ("inicial", "Trámite inicial"),
                    ("primera_prorroga", "Primera prórroga"),
                    ("segunda_prorroga", "Segunda prórroga"),
                    ("tercera_prorroga", "Tercera prórroga"),
                    ("cuarta_prorroga", "Cuarta prórroga"),
                    ("quinta_prorroga", "Quinta prórroga"),
                    ("sexta_prorroga", "Sexta prórroga"),
                    ("septima_prorroga", "Séptima prórroga"),
                    ("octava_prorroga", "Octava prórroga"),
                    ("otro", "Otro / No especificado"),
                ],
                default="otro",
                max_length=30,
                verbose_name="Trámite inicial o prórroga",
            ),
        ),
        migrations.AlterField(
            model_name="tramite",
            name="vobo_num_y_fecha",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="Número de oficio y fecha de Visto Bueno de la Subsecretaría",
            ),
        ),
    ]
