# Generated by Django 4.2.25 on 2025-10-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0006_cct_sostenimiento_controlinterno_sostenimiento"),
    ]

    operations = []
