# Generated by Django 4.2.25 on 2025-10-30 17:17

from django.db import migrations, models


def seed_defaults_forward(apps, schema_editor):
    replacements = (
        ("CCTSecundaria", "sostenimiento"),
        ("HistoricalCCTSecundaria", "sostenimiento"),
        ("ControlInterno", "sostenimiento_c_subcontrol"),
        ("HistoricalControlInterno", "sostenimiento_c_subcontrol"),
    )
    for model_name, field in replacements:
        Model = apps.get_model("licencias", model_name)
        Model.objects.filter(**{f"{field}__iexact": "FEDERAL TRANSFERIDO"}).update(**{field: "FEDERAL"})

    for model_name, field in (
        ("ControlInterno", "estatus"),
        ("HistoricalControlInterno", "estatus"),
    ):
        Model = apps.get_model("licencias", model_name)
        Model.objects.filter(**{f"{field}__isnull": True}).update(**{field: "NO ATENDIDO"})
        Model.objects.filter(**{field: ""}).update(**{field: "NO ATENDIDO"})


def seed_defaults_backward(apps, schema_editor):
    # The transformation is not reversible without additional information.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0007_normalize_sistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cctsecundaria",
            name="servicio",
            field=models.CharField(
                blank=True,
                help_text="Modalidad registrada en el catálogo tiponivelsub_c_servicion3.",
                max_length=255,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AlterField(
            model_name="cctsecundaria",
            name="sostenimiento",
            field=models.CharField(
                blank=True,
                help_text="Sistema registrado en el catálogo de secundarias.",
                max_length=255,
                verbose_name="Sistema",
            ),
        ),
        migrations.AlterField(
            model_name="controlinterno",
            name="sostenimiento_c_subcontrol",
            field=models.CharField(
                blank=True,
                help_text="Sistema del centro de trabajo.",
                max_length=255,
                verbose_name="Sistema",
            ),
        ),
        migrations.AlterField(
            model_name="controlinterno",
            name="tiponivelsub_c_servicion3",
            field=models.CharField(
                help_text="Modalidad educativa asociada al CCT.",
                max_length=255,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AlterField(
            model_name="controlinterno",
            name="estatus",
            field=models.CharField(
                blank=True,
                default="NO ATENDIDO",
                max_length=150,
                verbose_name="Estatus",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcctsecundaria",
            name="servicio",
            field=models.CharField(
                blank=True,
                help_text="Modalidad registrada en el catálogo tiponivelsub_c_servicion3.",
                max_length=255,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcctsecundaria",
            name="sostenimiento",
            field=models.CharField(
                blank=True,
                help_text="Sistema registrado en el catálogo de secundarias.",
                max_length=255,
                verbose_name="Sistema",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolinterno",
            name="sostenimiento_c_subcontrol",
            field=models.CharField(
                blank=True,
                help_text="Sistema del centro de trabajo.",
                max_length=255,
                verbose_name="Sistema",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolinterno",
            name="tiponivelsub_c_servicion3",
            field=models.CharField(
                help_text="Modalidad educativa asociada al CCT.",
                max_length=255,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrolinterno",
            name="estatus",
            field=models.CharField(
                blank=True,
                default="NO ATENDIDO",
                max_length=150,
                verbose_name="Estatus",
            ),
        ),
        migrations.RunPython(seed_defaults_forward, seed_defaults_backward),
    ]
