# Generated by Django 4.2.25 on 2025-11-25 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licencias", "0010_update_relacionprotocolo_sexo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("siglas", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Área de proceso",
                "verbose_name_plural": "Áreas de proceso",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CasoInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cct_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del CCT"),
                ),
                (
                    "cct_sistema",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sistema"
                    ),
                ),
                (
                    "cct_modalidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modalidad"
                    ),
                ),
                (
                    "asesor_cct",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asesor asignado"
                    ),
                ),
                (
                    "descripcion_breve",
                    models.CharField(max_length=255, verbose_name="Descripción breve"),
                ),
                ("fecha_apertura", models.DateField(verbose_name="Fecha de apertura")),
                (
                    "folio_inicial",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Folio inicial"
                    ),
                ),
                (
                    "fecha_oficio_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha oficio inicial"
                    ),
                ),
                (
                    "asunto_inicial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asunto inicial"
                    ),
                ),
                (
                    "observaciones_iniciales",
                    models.TextField(
                        blank=True, verbose_name="Observaciones iniciales"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caso interno",
                "verbose_name_plural": "Casos internos",
                "ordering": ("-fecha_apertura", "-fecha_registro"),
            },
        ),
        migrations.CreateModel(
            name="DocumentoCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(max_length=150, verbose_name="Tipo de documento"),
                ),
                ("archivo", models.FileField(upload_to="casos_internos/documentos/")),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Documento de caso",
                "verbose_name_plural": "Documentos de caso",
                "ordering": ("-fecha_subida",),
            },
        ),
        migrations.CreateModel(
            name="EstatusCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Estatus de caso",
                "verbose_name_plural": "Estatus de caso",
                "ordering": ("orden", "nombre"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstatusProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Estatus de proceso",
                "verbose_name_plural": "Estatus de proceso",
                "ordering": ("orden", "nombre"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistorialEstatusCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de cambio"
                    ),
                ),
                ("comentario", models.TextField(blank=True, verbose_name="Comentario")),
            ],
            options={
                "verbose_name": "Historial estatus de caso",
                "verbose_name_plural": "Historial estatus de casos",
                "ordering": ("-fecha_cambio",),
            },
        ),
        migrations.CreateModel(
            name="HistorialEstatusProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de cambio"
                    ),
                ),
                ("comentario", models.TextField(blank=True, verbose_name="Comentario")),
            ],
            options={
                "verbose_name": "Historial estatus de proceso",
                "verbose_name_plural": "Historial estatus de procesos",
                "ordering": ("-fecha_cambio",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalArea",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Área",
                "verbose_name_plural": "historical Áreas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAreaProceso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("siglas", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Área de proceso",
                "verbose_name_plural": "historical Áreas de proceso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCasoInterno",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cct_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del CCT"),
                ),
                (
                    "cct_sistema",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sistema"
                    ),
                ),
                (
                    "cct_modalidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modalidad"
                    ),
                ),
                (
                    "asesor_cct",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asesor asignado"
                    ),
                ),
                (
                    "descripcion_breve",
                    models.CharField(max_length=255, verbose_name="Descripción breve"),
                ),
                ("fecha_apertura", models.DateField(verbose_name="Fecha de apertura")),
                (
                    "folio_inicial",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Folio inicial"
                    ),
                ),
                (
                    "fecha_oficio_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha oficio inicial"
                    ),
                ),
                (
                    "asunto_inicial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asunto inicial"
                    ),
                ),
                (
                    "observaciones_iniciales",
                    models.TextField(
                        blank=True, verbose_name="Observaciones iniciales"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Caso interno",
                "verbose_name_plural": "historical Casos internos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDiagnostico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Diagnóstico",
                "verbose_name_plural": "historical Diagnósticos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEstatusCaso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Estatus de caso",
                "verbose_name_plural": "historical Estatus de caso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEstatusProceso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Estatus de proceso",
                "verbose_name_plural": "historical Estatus de proceso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEtapa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("es_final", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Etapa",
                "verbose_name_plural": "historical Etapas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProcesoInterno",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "folio",
                    models.CharField(max_length=150, verbose_name="Folio de oficio"),
                ),
                ("fecha_oficio", models.DateField(verbose_name="Fecha del oficio")),
                ("fecha_registro", models.DateTimeField(blank=True, editable=False)),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "cct_nombre",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre CCT"
                    ),
                ),
                (
                    "cct_sistema",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sistema"
                    ),
                ),
                (
                    "cct_modalidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modalidad"
                    ),
                ),
                (
                    "asesor_cct",
                    models.CharField(blank=True, max_length=255, verbose_name="Asesor"),
                ),
                (
                    "asesor_responsable",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asesor responsable"
                    ),
                ),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Proceso interno",
                "verbose_name_plural": "historical Procesos internos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResultado",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Resultado",
                "verbose_name_plural": "historical Resultados",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSindicato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sindicato",
                "verbose_name_plural": "historical Sindicatos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSubsistema",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Subsistema",
                "verbose_name_plural": "historical Subsistemas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTipoProceso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                (
                    "es_documento",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si generalmente genera o adjunta documento.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo de proceso",
                "verbose_name_plural": "historical Tipos de proceso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTipoTramite",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo de Trámite",
                "verbose_name_plural": "historical Tipos de Trámite",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProcesoInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folio",
                    models.CharField(max_length=150, verbose_name="Folio de oficio"),
                ),
                ("fecha_oficio", models.DateField(verbose_name="Fecha del oficio")),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "cct_nombre",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre CCT"
                    ),
                ),
                (
                    "cct_sistema",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sistema"
                    ),
                ),
                (
                    "cct_modalidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modalidad"
                    ),
                ),
                (
                    "asesor_cct",
                    models.CharField(blank=True, max_length=255, verbose_name="Asesor"),
                ),
                (
                    "asesor_responsable",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asesor responsable"
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proceso interno",
                "verbose_name_plural": "Procesos internos",
                "ordering": ("-fecha_oficio", "-fecha_registro"),
            },
        ),
        migrations.CreateModel(
            name="TipoProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "es_documento",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si generalmente genera o adjunta documento.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de proceso",
                "verbose_name_plural": "Tipos de proceso",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.RenameIndex(
            model_name="controlinterno",
            new_name="licencias_c_memoran_a6047f_idx",
            old_name="idx_controlinterno_memo",
        ),
        migrations.RenameIndex(
            model_name="controlinterno",
            new_name="licencias_c_anio_589414_idx",
            old_name="idx_controlinterno_anio",
        ),
        migrations.RenameIndex(
            model_name="controlinterno",
            new_name="licencias_c_cct_id_024d68_idx",
            old_name="idx_controlinterno_cct",
        ),
        migrations.RenameIndex(
            model_name="controlinterno",
            new_name="licencias_c_estatus_8f53b4_idx",
            old_name="idx_controlinterno_estatus",
        ),
        migrations.RenameIndex(
            model_name="relacionprotocolo",
            new_name="licencias_r_numero__99d112_idx",
            old_name="licencias_re_numero__4a0dc6_idx",
        ),
        migrations.RenameIndex(
            model_name="relacionprotocolo",
            new_name="licencias_r_anio_ad9f52_idx",
            old_name="licencias_re_anio_d3dce3_idx",
        ),
        migrations.RenameIndex(
            model_name="relacionprotocolo",
            new_name="licencias_r_estatus_2b718a_idx",
            old_name="licencias_re_estatus_471361_idx",
        ),
        migrations.RenameIndex(
            model_name="relacionprotocolo",
            new_name="licencias_r_cct_id_7108a4_idx",
            old_name="licencias_re_cct_e51b07_idx",
        ),
        migrations.RemoveField(
            model_name="historicalcctsecundaria",
            name="id",
        ),
        migrations.AlterField(
            model_name="historicalcontrolinterno",
            name="numero_interno",
            field=models.CharField(max_length=100, verbose_name="Número interno"),
        ),
        migrations.AlterField(
            model_name="historicalrelacionprotocolo",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de inicio"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrelacionprotocolo",
            name="numero_registro",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="Identificador correlativo utilizado en el control vigente",
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="relacionprotocolo",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de inicio"
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="area_destino",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos_destino",
                to="licencias.areaproceso",
                verbose_name="Área de destino",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="area_origen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos_origen",
                to="licencias.areaproceso",
                verbose_name="Área de origen",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="caso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="procesos",
                to="licencias.casointerno",
                verbose_name="Caso",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="cct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos_internos",
                to="licencias.cctsecundaria",
                verbose_name="CCT",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="procesos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="estatus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos",
                to="licencias.estatusproceso",
                verbose_name="Estatus",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="proceso_padre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subprocesos",
                to="licencias.procesointerno",
                verbose_name="Proceso padre",
            ),
        ),
        migrations.AddField(
            model_name="procesointerno",
            name="tipo_proceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos",
                to="licencias.tipoproceso",
                verbose_name="Tipo de proceso",
            ),
        ),
        migrations.AddField(
            model_name="historicaltipotramite",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltipoproceso",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsubsistema",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsindicato",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalresultado",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="area_destino",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.areaproceso",
                verbose_name="Área de destino",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="area_origen",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.areaproceso",
                verbose_name="Área de origen",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="caso",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.casointerno",
                verbose_name="Caso",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="cct",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.cctsecundaria",
                verbose_name="CCT",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="estatus",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.estatusproceso",
                verbose_name="Estatus",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="proceso_padre",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.procesointerno",
                verbose_name="Proceso padre",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesointerno",
            name="tipo_proceso",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.tipoproceso",
                verbose_name="Tipo de proceso",
            ),
        ),
        migrations.AddField(
            model_name="historicaletapa",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalestatusproceso",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalestatuscaso",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldiagnostico",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="area_origen_inicial",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.areaproceso",
                verbose_name="Área de origen",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="cct",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.cctsecundaria",
                verbose_name="CCT principal",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="estatus",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.estatuscaso",
                verbose_name="Estatus",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="tipo_inicial",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.tipoproceso",
                verbose_name="Tipo inicial",
            ),
        ),
        migrations.AddField(
            model_name="historicalareaproceso",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalarea",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialestatusproceso",
            name="estatus_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="licencias.estatusproceso",
                verbose_name="Estatus anterior",
            ),
        ),
        migrations.AddField(
            model_name="historialestatusproceso",
            name="estatus_nuevo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="licencias.estatusproceso",
                verbose_name="Estatus nuevo",
            ),
        ),
        migrations.AddField(
            model_name="historialestatusproceso",
            name="proceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_estatus",
                to="licencias.procesointerno",
                verbose_name="Proceso",
            ),
        ),
        migrations.AddField(
            model_name="historialestatusproceso",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_estatus_procesos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="historialestatuscaso",
            name="caso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_estatus",
                to="licencias.casointerno",
                verbose_name="Caso",
            ),
        ),
        migrations.AddField(
            model_name="historialestatuscaso",
            name="estatus_anterior",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="licencias.estatuscaso",
                verbose_name="Estatus anterior",
            ),
        ),
        migrations.AddField(
            model_name="historialestatuscaso",
            name="estatus_nuevo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="licencias.estatuscaso",
                verbose_name="Estatus nuevo",
            ),
        ),
        migrations.AddField(
            model_name="historialestatuscaso",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_estatus_casos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="documentocaso",
            name="proceso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="licencias.procesointerno",
                verbose_name="Proceso",
            ),
        ),
        migrations.AddField(
            model_name="documentocaso",
            name="subido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_casos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="area_origen_inicial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos_origen",
                to="licencias.areaproceso",
                verbose_name="Área de origen",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="cct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos_internos",
                to="licencias.cctsecundaria",
                verbose_name="CCT principal",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="casos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="estatus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos",
                to="licencias.estatuscaso",
                verbose_name="Estatus",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="tipo_inicial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos_iniciados_como",
                to="licencias.tipoproceso",
                verbose_name="Tipo inicial",
            ),
        ),
        migrations.AddIndex(
            model_name="procesointerno",
            index=models.Index(fields=["folio"], name="licencias_p_folio_8f27f7_idx"),
        ),
        migrations.AddIndex(
            model_name="procesointerno",
            index=models.Index(fields=["caso"], name="licencias_p_caso_id_9c14d2_idx"),
        ),
        migrations.AddIndex(
            model_name="procesointerno",
            index=models.Index(fields=["cct"], name="licencias_p_cct_id_575eca_idx"),
        ),
        migrations.AddIndex(
            model_name="procesointerno",
            index=models.Index(
                fields=["tipo_proceso"], name="licencias_p_tipo_pr_50150a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procesointerno",
            index=models.Index(
                fields=["estatus"], name="licencias_p_estatus_faa973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casointerno",
            index=models.Index(fields=["cct"], name="licencias_c_cct_id_a29181_idx"),
        ),
        migrations.AddIndex(
            model_name="casointerno",
            index=models.Index(
                fields=["estatus"], name="licencias_c_estatus_0d09d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casointerno",
            index=models.Index(
                fields=["fecha_apertura"], name="licencias_c_fecha_a_9083cf_idx"
            ),
        ),
    ]
