# Generated by Django 4.2.25 on 2025-12-05 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("siglas", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Área de proceso",
                "verbose_name_plural": "Áreas de proceso",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CasoInterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cct_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del CCT"),
                ),
                (
                    "cct_sistema",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sistema"
                    ),
                ),
                (
                    "cct_modalidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modalidad"
                    ),
                ),
                (
                    "asesor_cct",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asesor asignado"
                    ),
                ),
                (
                    "descripcion_breve",
                    models.CharField(max_length=255, verbose_name="Descripción breve"),
                ),
                ("fecha_apertura", models.DateField(verbose_name="Fecha de apertura")),
                (
                    "folio_inicial",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Folio inicial"
                    ),
                ),
                (
                    "fecha_oficio_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha oficio inicial"
                    ),
                ),
                (
                    "asunto_inicial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asunto inicial"
                    ),
                ),
                (
                    "observaciones_iniciales",
                    models.TextField(
                        blank=True, verbose_name="Observaciones iniciales"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "area_origen_inicial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos_origen",
                        to="licencias.areaproceso",
                        verbose_name="Área de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trámite",
                "verbose_name_plural": "Trámites",
                "ordering": ("-fecha_apertura", "-fecha_registro"),
            },
        ),
        migrations.CreateModel(
            name="CCTSecundaria",
            fields=[
                (
                    "cct",
                    models.CharField(
                        help_text="Clave de centro de trabajo",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="CCT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la escuela"
                    ),
                ),
                (
                    "asesor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Asesor jurídico asignado",
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        blank=True,
                        help_text="Modalidad registrada en el catálogo tiponivelsub_c_servicion3.",
                        max_length=255,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "sostenimiento",
                    models.CharField(
                        blank=True,
                        help_text="Sistema registrado en el catálogo de secundarias.",
                        max_length=255,
                        verbose_name="Sistema",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Municipio"
                    ),
                ),
                (
                    "turno",
                    models.CharField(blank=True, max_length=255, verbose_name="Turno"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Centro de trabajo (Secundaria)",
                "verbose_name_plural": "Centros de trabajo (Secundaria)",
                "ordering": ("cct",),
            },
        ),
        migrations.CreateModel(
            name="EstatusCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Estatus de caso",
                "verbose_name_plural": "Estatus de caso",
                "ordering": ("orden", "nombre"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TipoProceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "es_documento",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si requiere documentos adicionales.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de trámite",
                "verbose_name_plural": "Tipos de trámite",
                "ordering": ("nombre",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalTipoProceso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                (
                    "es_documento",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si requiere documentos adicionales.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo de trámite",
                "verbose_name_plural": "historical Tipos de trámite",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEstatusCaso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Estatus de caso",
                "verbose_name_plural": "historical Estatus de caso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCCTSecundaria",
            fields=[
                (
                    "cct",
                    models.CharField(
                        db_index=True,
                        help_text="Clave de centro de trabajo",
                        max_length=12,
                        verbose_name="CCT",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la escuela"
                    ),
                ),
                (
                    "asesor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Asesor jurídico asignado",
                    ),
                ),
                (
                    "servicio",
                    models.CharField(
                        blank=True,
                        help_text="Modalidad registrada en el catálogo tiponivelsub_c_servicion3.",
                        max_length=255,
                        verbose_name="Modalidad",
                    ),
                ),
                (
                    "sostenimiento",
                    models.CharField(
                        blank=True,
                        help_text="Sistema registrado en el catálogo de secundarias.",
                        max_length=255,
                        verbose_name="Sistema",
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Municipio"
                    ),
                ),
                (
                    "turno",
                    models.CharField(blank=True, max_length=255, verbose_name="Turno"),
                ),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Centro de trabajo (Secundaria)",
                "verbose_name_plural": "historical Centros de trabajo (Secundaria)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCasoInterno",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cct_nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del CCT"),
                ),
                (
                    "cct_sistema",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sistema"
                    ),
                ),
                (
                    "cct_modalidad",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modalidad"
                    ),
                ),
                (
                    "asesor_cct",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asesor asignado"
                    ),
                ),
                (
                    "descripcion_breve",
                    models.CharField(max_length=255, verbose_name="Descripción breve"),
                ),
                ("fecha_apertura", models.DateField(verbose_name="Fecha de apertura")),
                (
                    "folio_inicial",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Folio inicial"
                    ),
                ),
                (
                    "fecha_oficio_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha oficio inicial"
                    ),
                ),
                (
                    "asunto_inicial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Asunto inicial"
                    ),
                ),
                (
                    "observaciones_iniciales",
                    models.TextField(
                        blank=True, verbose_name="Observaciones iniciales"
                    ),
                ),
                ("fecha_registro", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "area_origen_inicial",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.areaproceso",
                        verbose_name="Área de origen",
                    ),
                ),
                (
                    "cct",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.cctsecundaria",
                        verbose_name="CCT principal",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "estatus",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.estatuscaso",
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_inicial",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="licencias.tipoproceso",
                        verbose_name="Tipo inicial",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Trámite",
                "verbose_name_plural": "historical Trámites",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAreaProceso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("siglas", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Área de proceso",
                "verbose_name_plural": "historical Áreas de proceso",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistorialEstatusCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de cambio"
                    ),
                ),
                ("comentario", models.TextField(blank=True, verbose_name="Comentario")),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estatus",
                        to="licencias.casointerno",
                        verbose_name="Caso",
                    ),
                ),
                (
                    "estatus_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="licencias.estatuscaso",
                        verbose_name="Estatus anterior",
                    ),
                ),
                (
                    "estatus_nuevo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="licencias.estatuscaso",
                        verbose_name="Estatus nuevo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_estatus_casos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de estatus de trámite",
                "verbose_name_plural": "Historial de estatus de trámites",
                "ordering": ("-fecha_cambio",),
            },
        ),
        migrations.AddField(
            model_name="casointerno",
            name="cct",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos",
                to="licencias.cctsecundaria",
                verbose_name="CCT principal",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="casos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado por",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="estatus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos",
                to="licencias.estatuscaso",
                verbose_name="Estatus",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="tipo_inicial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="casos_iniciados_como",
                to="licencias.tipoproceso",
                verbose_name="Tipo inicial",
            ),
        ),
        migrations.AddIndex(
            model_name="casointerno",
            index=models.Index(fields=["cct"], name="licencias_c_cct_id_a29181_idx"),
        ),
        migrations.AddIndex(
            model_name="casointerno",
            index=models.Index(
                fields=["estatus"], name="licencias_c_estatus_0d09d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casointerno",
            index=models.Index(
                fields=["fecha_apertura"], name="licencias_c_fecha_a_9083cf_idx"
            ),
        ),
    ]
