# Generated by Django 4.2.27 on 2025-12-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0013_funcion_solicitante_destinatario"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcasointerno",
            name="fecha_termino",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de término"
            ),
        ),
        migrations.AddField(
            model_name="historicaldestinatario",
            name="funcion",
            field=models.CharField(blank=True, max_length=255, verbose_name="Función"),
        ),
        migrations.AddField(
            model_name="historicalsolicitante",
            name="funcion",
            field=models.CharField(blank=True, max_length=255, verbose_name="Función"),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="fecha_termino",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de término"
            ),
        ),
    ]
