# Generated by Django 4.2.27 on 2025-12-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0015_remove_funcion_use_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casointerno',
            name='incidencia_afiliacion',
            field=models.CharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE')], max_length=10, verbose_name='Afiliación (IMSS/ISSSTE)'),
        ),
        migrations.AddField(
            model_name='casointerno',
            name='incidencia_dias_otorgados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días otorgados (naturales)'),
        ),
        migrations.AddField(
            model_name='casointerno',
            name='incidencia_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de incidencia'),
        ),
        migrations.AddField(
            model_name='casointerno',
            name='incidencia_fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha término de incidencia'),
        ),
        migrations.AddField(
            model_name='casointerno',
            name='incidencia_nombre_docente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del docente'),
        ),
        migrations.AddField(
            model_name='historicalcasointerno',
            name='incidencia_afiliacion',
            field=models.CharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE')], max_length=10, verbose_name='Afiliación (IMSS/ISSSTE)'),
        ),
        migrations.AddField(
            model_name='historicalcasointerno',
            name='incidencia_dias_otorgados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días otorgados (naturales)'),
        ),
        migrations.AddField(
            model_name='historicalcasointerno',
            name='incidencia_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de incidencia'),
        ),
        migrations.AddField(
            model_name='historicalcasointerno',
            name='incidencia_fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha término de incidencia'),
        ),
        migrations.AddField(
            model_name='historicalcasointerno',
            name='incidencia_nombre_docente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del docente'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='incidencia_afiliacion',
            field=models.CharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE')], max_length=10, verbose_name='Afiliación (IMSS/ISSSTE)'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='incidencia_dias_otorgados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días otorgados (naturales)'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='incidencia_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de incidencia'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='incidencia_fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha término de incidencia'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='incidencia_nombre_docente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del docente'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='incidencia_afiliacion',
            field=models.CharField(blank=True, choices=[('IMSS', 'IMSS'), ('ISSSTE', 'ISSSTE')], max_length=10, verbose_name='Afiliación (IMSS/ISSSTE)'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='incidencia_dias_otorgados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Días otorgados (naturales)'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='incidencia_fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio de incidencia'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='incidencia_fecha_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha término de incidencia'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='incidencia_nombre_docente',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del docente'),
        ),
    ]
