# Generated by Codex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0019_expand_plantilla_telefono"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstatusLicencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Estatus de licencia",
                "verbose_name_plural": "Estatus de licencias",
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="LicenciaRegistro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trabajador_correo", models.EmailField(blank=True, max_length=254, verbose_name="Correo trabajador")),
                ("trabajador_celular", models.CharField(blank=True, max_length=50, verbose_name="Celular trabajador")),
                ("trabajador_sistema", models.CharField(blank=True, max_length=255, verbose_name="Federal/Estatal")),
                (
                    "tipo_tramite",
                    models.CharField(
                        choices=[
                            ("licencia_754", "Licencia 754"),
                            ("cambio_funcion", "Cambio de función"),
                            ("licencia_70_bis", "Licencia 70 BIS"),
                            ("cambio_actividad", "Cambio de actividad"),
                        ],
                        max_length=30,
                        verbose_name="Licencia o trámite",
                    ),
                ),
                (
                    "tipo_prorroga",
                    models.CharField(
                        choices=[
                            ("inicial", "Inicial"),
                            ("primera_prorroga", "Primera prórroga"),
                            ("segunda_prorroga", "Segunda prórroga"),
                            ("tercera_prorroga", "Tercera prórroga"),
                            ("cuarta_prorroga", "Cuarta prórroga"),
                            ("quinta_prorroga", "Quinta prórroga"),
                        ],
                        max_length=30,
                        verbose_name="Trámite inicial o prórroga",
                    ),
                ),
                (
                    "sindicato",
                    models.CharField(
                        choices=[
                            ("sytte", "SYTTE"),
                            ("snte_33", "SNTE sección 33"),
                            ("snte_57", "SNTE sección 57"),
                            ("setey", "SETEY"),
                            ("gnte", "GNTE"),
                            ("sitem", "SITEM"),
                        ],
                        max_length=30,
                        verbose_name="Nombre del sindicato",
                    ),
                ),
                ("fecha_tramite", models.DateField(verbose_name="Fecha del trámite")),
                (
                    "numero_expediente",
                    models.CharField(blank=True, max_length=150, verbose_name="Número de expediente (solicitud inicial)"),
                ),
                (
                    "respuesta_oficio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("subsecretaria_basica_prorrogas", "Oficio de envío a la Subsecretaría Básica / Prórrogas"),
                            ("subd_org_personal_daf", "Oficio de envío a la Subd. de Org. y Adm. de Personal - DAF"),
                            ("incidencias_integracion", "Incidencias para la integración del expediente"),
                            ("prevencion", "Prevención del trámite"),
                            ("contestacion_negativa", "Contestación negativa del trámite"),
                        ],
                        max_length=50,
                        verbose_name="Respuesta de oficio a",
                    ),
                ),
                (
                    "respuesta_numero_expediente",
                    models.CharField(blank=True, max_length=150, verbose_name="Número de expediente (respuesta)"),
                ),
                (
                    "respuesta_fecha_recepcion",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de recepción (respuesta)"),
                ),
                (
                    "visto_bueno",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visto_bueno_subsecretaria_basica", "Visto bueno por la Subsecretaría Básica"),
                            ("incidencias_visto_bueno", "Incidencias para el visto bueno de la Subsecretaría"),
                        ],
                        max_length=50,
                        verbose_name="Visto bueno por",
                    ),
                ),
                (
                    "visto_bueno_numero_expediente",
                    models.CharField(blank=True, max_length=150, verbose_name="Número de expediente (visto bueno)"),
                ),
                ("visto_bueno_fecha", models.DateField(blank=True, null=True, verbose_name="Fecha de visto bueno")),
                (
                    "fecha_recepcion_daf",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de recepción por la Subd. de Org. y Adm. de Personal - DAF",
                    ),
                ),
                (
                    "aplica_estatal",
                    models.BooleanField(default=False, verbose_name="Aplica para trámites estatales o prórrogas"),
                ),
                (
                    "cita_valoracion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cita_valoracion", "Cita de valoración del trabajador"),
                            ("incidencias_contacto", "Incidencias en el contacto para la cita de valoración"),
                        ],
                        max_length=50,
                        verbose_name="Cita de valoración o incidencia",
                    ),
                ),
                (
                    "cita_valoracion_numero_expediente",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Número de expediente (cita/valoración)"
                    ),
                ),
                (
                    "cita_valoracion_fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de la cita de valoración del trabajador"),
                ),
                (
                    "fecha_contacto",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de contacto al sindicato y al trabajador"
                    ),
                ),
                (
                    "dictamen_numero_expediente",
                    models.CharField(blank=True, max_length=150, verbose_name="Número de expediente del dictamen"),
                ),
                ("dictamen_fecha", models.DateField(blank=True, null=True, verbose_name="Fecha del dictamen")),
                ("dictamen_periodo_de", models.DateField(blank=True, null=True, verbose_name="Periodo de")),
                ("dictamen_periodo_hasta", models.DateField(blank=True, null=True, verbose_name="Periodo hasta")),
                (
                    "notificacion_numero_expediente",
                    models.CharField(blank=True, max_length=150, verbose_name="Número de expediente de la notificación"),
                ),
                (
                    "notificacion_fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha de la notificación"),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licencias_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
                (
                    "estatus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="licencias.estatuslicencia",
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="licencias.plantillaempleado",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Licencia",
                "verbose_name_plural": "Licencias",
                "ordering": ("-fecha_tramite", "-fecha_registro"),
            },
        ),
        migrations.CreateModel(
            name="HistorialEstatusLicencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha_cambio", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de cambio")),
                ("comentario", models.TextField(blank=True, verbose_name="Comentario")),
                (
                    "estatus_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="licencias.estatuslicencia",
                        verbose_name="Estatus anterior",
                    ),
                ),
                (
                    "estatus_nuevo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="licencias.estatuslicencia",
                        verbose_name="Estatus nuevo",
                    ),
                ),
                (
                    "licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estatus",
                        to="licencias.licenciaregistro",
                        verbose_name="Licencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cambios_estatus_licencias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de estatus de licencia",
                "verbose_name_plural": "Historial de estatus de licencias",
                "ordering": ("-fecha_cambio",),
            },
        ),
        migrations.AddIndex(
            model_name="licenciaregistro",
            index=models.Index(fields=["trabajador"], name="licencias_li_trabaja_d2f3c7_idx"),
        ),
        migrations.AddIndex(
            model_name="licenciaregistro",
            index=models.Index(fields=["estatus"], name="licencias_li_estatus_1c1c47_idx"),
        ),
        migrations.AddIndex(
            model_name="licenciaregistro",
            index=models.Index(fields=["fecha_tramite"], name="licencias_li_fecha_t_c1f574_idx"),
        ),
    ]
