# Generated by Django 4.2.27 on 2026-01-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0020_licencias"),
        ("licencias", "0023_caso_usuarios_involucrados"),
    ]

    operations = []
