# Generated by Codex on 2026-01-29
from django.db import migrations, models
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0025_bandeja_notificaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="tramitecaso",
            name="es_iniciador",
            field=models.BooleanField(default=False, verbose_name="Trámite iniciador del caso"),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="es_iniciador",
            field=models.BooleanField(default=False, verbose_name="Trámite iniciador del caso"),
        ),
        migrations.AddConstraint(
            model_name="tramitecaso",
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(("es_iniciador", True)),
                fields=("caso",),
                name="tramites_un_iniciador_por_caso",
            ),
        ),
    ]
