# Generated by Codex on 2026-01-29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0026_tramite_iniciador"),
    ]

    operations = [
        migrations.AddField(
            model_name="casointerno",
            name="generadores_adicionales",
            field=models.JSONField(default=list, blank=True, verbose_name="Generadores adicionales"),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="generadores_adicionales",
            field=models.JSONField(default=list, blank=True, verbose_name="Generadores adicionales"),
        ),
        migrations.AddField(
            model_name="tramitecaso",
            name="generadores_adicionales",
            field=models.JSONField(default=list, blank=True, verbose_name="Generadores adicionales"),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="generadores_adicionales",
            field=models.JSONField(default=list, blank=True, verbose_name="Generadores adicionales"),
        ),
    ]
