# Generated by Django 4.2.27 on 2026-01-29 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licencias", "0027_generadores_adicionales"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalEstatusLicencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(blank=True, editable=False)),
                ("actualizado_en", models.DateTimeField(blank=True, editable=False)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Estatus de licencia",
                "verbose_name_plural": "historical Estatus de licencias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RenameIndex(
            model_name="licenciaregistro",
            new_name="licencias_l_trabaja_b373f7_idx",
            old_name="licencias_li_trabaja_d2f3c7_idx",
        ),
        migrations.RenameIndex(
            model_name="licenciaregistro",
            new_name="licencias_l_estatus_f9793f_idx",
            old_name="licencias_li_estatus_1c1c47_idx",
        ),
        migrations.RenameIndex(
            model_name="licenciaregistro",
            new_name="licencias_l_fecha_t_69a5ad_idx",
            old_name="licencias_li_fecha_t_c1f574_idx",
        ),
        migrations.RenameIndex(
            model_name="plantillaregistro",
            new_name="licencias_p_ciclo_9b5f50_idx",
            old_name="plantilla_ciclo_idx",
        ),
        migrations.RenameIndex(
            model_name="plantillaregistro",
            new_name="licencias_p_emplead_4eec55_idx",
            old_name="plantilla_empleado_anio_idx",
        ),
        migrations.AlterField(
            model_name="bandejanotificacion",
            name="evento",
            field=models.CharField(
                choices=[
                    ("caso_creado", "Caso creado"),
                    ("caso_actualizado", "Caso actualizado"),
                    ("caso_estatus", "Estatus de caso actualizado"),
                    ("caso_eliminado", "Caso eliminado"),
                    ("tramite_creado", "Trámite asociado creado"),
                    ("tramite_actualizado", "Trámite asociado actualizado"),
                    ("tramite_estatus", "Estatus de trámite actualizado"),
                    ("tramite_eliminado", "Trámite asociado eliminado"),
                    ("minuta_eliminada", "Minuta eliminada"),
                    ("registro_leido", "Registro leído"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="casointerno",
            name="minuta",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tramites/minutas/casos/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Documento (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasointerno",
            name="minuta",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Documento (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltramitecaso",
            name="minuta",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Documento (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="tramitecaso",
            name="minuta",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="tramites/minutas/tramites/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                verbose_name="Documento (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="historicalestatuslicencia",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
