# Generated by Codex on 2026-01-29
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licencias", "0028_historicalestatuslicencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolioConsecutivo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anio", models.PositiveIntegerField(db_index=True, verbose_name="Año")),
                ("prefijo", models.CharField(max_length=255, verbose_name="Prefijo")),
                ("ultimo_numero", models.PositiveIntegerField(default=0, verbose_name="Último número")),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("actualizado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="folios_actualizados", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Consecutivo de folio",
                "verbose_name_plural": "Consecutivos de folio",
                "unique_together": {("anio", "prefijo")},
            },
        ),
        migrations.CreateModel(
            name="FolioRegistro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("anio", models.PositiveIntegerField(db_index=True, verbose_name="Año")),
                ("prefijo", models.CharField(max_length=255, verbose_name="Prefijo")),
                ("numero", models.PositiveIntegerField(verbose_name="Número")),
                ("folio", models.CharField(db_index=True, max_length=255, verbose_name="Folio completo")),
                ("tipo", models.CharField(choices=[("caso", "Caso"), ("tramite", "Trámite anexo")], max_length=20)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                ("eliminado_en", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("caso", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="folios_generados", to="licencias.casointerno")),
                ("creado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="folios_creados", to=settings.AUTH_USER_MODEL)),
                ("eliminado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="folios_eliminados", to=settings.AUTH_USER_MODEL)),
                ("tramite", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="folios_generados", to="licencias.tramitecaso")),
            ],
            options={
                "verbose_name": "Registro de folio",
                "verbose_name_plural": "Registros de folio",
            },
        ),
        migrations.AddIndex(
            model_name="folioregistro",
            index=models.Index(fields=["anio", "prefijo"], name="licencias_folio_anio_prefijo_idx"),
        ),
    ]
