# Generated by Codex on 2026-01-29
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licencias", "0029_folios"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolioActividad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("accion", models.CharField(choices=[("creado", "Creado"), ("editado", "Editado"), ("eliminado", "Eliminado")], max_length=20)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("detalle", models.TextField(blank=True)),
                ("folio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="actividades", to="licencias.folioregistro")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="folios_actividades", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Actividad de folio",
                "verbose_name_plural": "Actividades de folios",
                "ordering": ("-creado_en",),
            },
        ),
    ]
