# Generated by Codex on 2026-01-29
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0030_folio_actividad"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolioPrefijo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prefijo de folio",
                "verbose_name_plural": "Prefijos de folio",
                "ordering": ("nombre",),
            },
        ),
    ]
