# Generated by Django 4.2.27 on 2026-01-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0031_folio_prefijo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcctsecundaria",
            name="history_user",
        ),
        migrations.RenameIndex(
            model_name="folioregistro",
            new_name="licencias_f_anio_efb713_idx",
            old_name="licencias_folio_anio_prefijo_idx",
        ),
        migrations.DeleteModel(
            name="HistoricalCCTSecundaria",
        ),
    ]
