# Generated by Django 4.2.27 on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0033_tipos_violencia_adicionales"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcasointerno",
            name="tipos_violencia_adicionales",
            field=models.JSONField(blank=True, default=list, verbose_name="Tipos de violencia adicionales"),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="tipos_violencia_adicionales",
            field=models.JSONField(blank=True, default=list, verbose_name="Tipos de violencia adicionales"),
        ),
    ]
