# Generated by Django 4.2.27 on 2026-02-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0030_bitacora_caso"),
        (
            "licencias",
            "0034_historicalcasointerno_tipos_violencia_adicionales_and_more",
        ),
    ]

    operations = []
