# Generated by Django 4.2.27 on 2026-02-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0036_trabajadores_caso_y_cct_plantilla"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="plantillaregistro",
            new_name="pl_reg_emp_anio_ciclo_idx",
            old_name="plantilla_reg_empleado_anio_ciclo_idx",
        ),
        migrations.AddField(
            model_name="casointerno",
            name="centros_trabajo_adicionales",
            field=models.ManyToManyField(
                blank=True,
                related_name="casos_adicionales",
                to="licencias.plantillacentrotrabajo",
                verbose_name="Centros de trabajo adicionales",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcasointerno",
            name="cct",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="licencias.plantillacentrotrabajo",
                verbose_name="CCT principal",
            ),
        ),
    ]
