# Generated by Codex on 2026-02-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0037_rename_plantilla_reg_empleado_anio_ciclo_idx_licencias_p_emplead_93f25c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folioregistro",
            name="casos",
            field=models.ManyToManyField(
                blank=True,
                related_name="folios_generados_m2m",
                to="licencias.casointerno",
            ),
        ),
    ]
