# Generated by Codex on 2026-02-09
from django.db import migrations


def forwards(apps, schema_editor):
    FolioRegistro = apps.get_model("licencias", "FolioRegistro")
    through = FolioRegistro.casos.through
    rows = (
        FolioRegistro.objects.exclude(caso__isnull=True)
        .values_list("id", "caso_id")
    )
    to_create = [
        through(folioregistro_id=folio_id, casointerno_id=caso_id)
        for folio_id, caso_id in rows
        if caso_id
    ]
    if to_create:
        through.objects.bulk_create(to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0038_folioregistro_casos_m2m"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
