# Generated by Codex on 2026-02-09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0039_migrate_folioregistro_casos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folioregistro",
            name="caso",
        ),
        migrations.AlterField(
            model_name="folioregistro",
            name="casos",
            field=models.ManyToManyField(
                blank=True,
                related_name="folios_generados",
                to="licencias.casointerno",
            ),
        ),
    ]
