# Generated by Codex on 2026-02-09
from django.db import migrations, models


TIPO_PRORROGA_CHOICES = [
    ("inicial", "Inicial"),
    ("primera_prorroga", "Primera prórroga"),
    ("segunda_prorroga", "Segunda prórroga"),
    ("tercera_prorroga", "Tercera prórroga"),
    ("cuarta_prorroga", "Cuarta prórroga"),
    ("quinta_prorroga", "Quinta prórroga"),
]

SINDICATO_CHOICES = [
    ("sytte", "SYTTE"),
    ("snte_33", "SNTE sección 33"),
    ("snte_57", "SNTE sección 57"),
    ("setey", "SETEY"),
    ("gnte", "GNTE"),
    ("sitem", "SITEM"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0040_remove_folioregistro_caso"),
    ]

    operations = [
        migrations.AddField(
            model_name="casointerno",
            name="tipo_prorroga",
            field=models.CharField(
                blank=True,
                choices=TIPO_PRORROGA_CHOICES,
                default="",
                max_length=30,
                verbose_name="Trámite inicial o prórroga",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="sindicato",
            field=models.CharField(
                blank=True,
                choices=SINDICATO_CHOICES,
                default="",
                max_length=30,
                verbose_name="Nombre del sindicato",
            ),
        ),
        migrations.AddField(
            model_name="casointerno",
            name="diagnostico",
            field=models.TextField(blank=True, default="", verbose_name="Diagnóstico"),
        ),
        migrations.AddField(
            model_name="tramitecaso",
            name="tipo_prorroga",
            field=models.CharField(
                blank=True,
                choices=TIPO_PRORROGA_CHOICES,
                default="",
                max_length=30,
                verbose_name="Trámite inicial o prórroga",
            ),
        ),
        migrations.AddField(
            model_name="tramitecaso",
            name="sindicato",
            field=models.CharField(
                blank=True,
                choices=SINDICATO_CHOICES,
                default="",
                max_length=30,
                verbose_name="Nombre del sindicato",
            ),
        ),
        migrations.AddField(
            model_name="tramitecaso",
            name="diagnostico",
            field=models.TextField(blank=True, default="", verbose_name="Diagnóstico"),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="tipo_prorroga",
            field=models.CharField(
                blank=True,
                choices=TIPO_PRORROGA_CHOICES,
                default="",
                max_length=30,
                verbose_name="Trámite inicial o prórroga",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="sindicato",
            field=models.CharField(
                blank=True,
                choices=SINDICATO_CHOICES,
                default="",
                max_length=30,
                verbose_name="Nombre del sindicato",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="diagnostico",
            field=models.TextField(blank=True, default="", verbose_name="Diagnóstico"),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="tipo_prorroga",
            field=models.CharField(
                blank=True,
                choices=TIPO_PRORROGA_CHOICES,
                default="",
                max_length=30,
                verbose_name="Trámite inicial o prórroga",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="sindicato",
            field=models.CharField(
                blank=True,
                choices=SINDICATO_CHOICES,
                default="",
                max_length=30,
                verbose_name="Nombre del sindicato",
            ),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="diagnostico",
            field=models.TextField(blank=True, default="", verbose_name="Diagnóstico"),
        ),
    ]
