# Generated by Django 4.2.27 on 2026-02-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0041_caso_tramite_licencias_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='asesor_cct',
            field=models.CharField(blank=True, max_length=255, verbose_name='Asesor asignado'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='cct',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='licencias.plantillacentrotrabajo', verbose_name='CCT del trámite'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='cct_modalidad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='cct_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del CCT'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='cct_sistema',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sistema'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='asesor_cct',
            field=models.CharField(blank=True, max_length=255, verbose_name='Asesor asignado'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='cct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_asociados', to='licencias.plantillacentrotrabajo', verbose_name='CCT del trámite'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='cct_modalidad',
            field=models.CharField(blank=True, max_length=255, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='cct_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del CCT'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='cct_sistema',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sistema'),
        ),
    ]
