# Generated by Codex on 2026-02-12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0042_tramite_caso_cct_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="casointerno",
            name="trabajadores_manuales",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Trabajadores capturados localmente para este caso sin afectar la plantilla.",
                verbose_name="Trabajadores manuales del caso",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="trabajadores_manuales",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Trabajadores capturados localmente para este caso sin afectar la plantilla.",
                verbose_name="Trabajadores manuales del caso",
            ),
        ),
    ]
