# Generated by Django 4.2.25 on 2026-02-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0043_casointerno_trabajadores_manuales"),
    ]

    operations = [
        migrations.AddField(
            model_name="casointerno",
            name="rangos_fechas_adicionales",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rangos de fechas adicionales"
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="rangos_fechas_adicionales",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rangos de fechas adicionales"
            ),
        ),
        migrations.AddField(
            model_name="historicaltramitecaso",
            name="rangos_fechas_adicionales",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rangos de fechas adicionales"
            ),
        ),
        migrations.AddField(
            model_name="tramitecaso",
            name="rangos_fechas_adicionales",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Rangos de fechas adicionales"
            ),
        ),
    ]
