# Generated by Django 4.2.28 on 2026-02-16 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


FEATURE_FLAGS_SEED = [
    {
        "codigo": "module_tramites",
        "modulo": "tramites",
        "nombre": "Módulo de trámites",
        "descripcion": "Controla acceso al módulo principal de trámites, bandeja y folios.",
        "habilitado": True,
        "habilitado_por_defecto": True,
    },
    {
        "codigo": "module_licencias",
        "modulo": "licencias",
        "nombre": "Módulo de licencias",
        "descripcion": "Controla acceso al módulo de licencias.",
        "habilitado": True,
        "habilitado_por_defecto": True,
    },
    {
        "codigo": "module_reportes",
        "modulo": "reportes",
        "nombre": "Módulo de reportes",
        "descripcion": "Controla acceso a reportes y exportaciones.",
        "habilitado": True,
        "habilitado_por_defecto": True,
    },
    {
        "codigo": "module_herramientas",
        "modulo": "herramientas",
        "nombre": "Módulo de herramientas",
        "descripcion": "Controla acceso al centro de herramientas.",
        "habilitado": True,
        "habilitado_por_defecto": True,
    },
    {
        "codigo": "module_gobierno_datos",
        "modulo": "gobierno_datos",
        "nombre": "Gobierno de datos",
        "descripcion": "Controla acceso al panel E1 de auditoría, flags y calidad de datos.",
        "habilitado": True,
        "habilitado_por_defecto": True,
    },
]

SCHEDULED_JOBS_SEED = [
    {
        "codigo": "data-quality-hourly",
        "nombre": "Calidad de datos cada hora",
        "descripcion": "Escaneo de datos incompletos, duplicados e inconsistentes.",
        "handler": "data_quality_scan",
        "intervalo_minutos": 60,
        "activo": True,
    },
    {
        "codigo": "healthcheck-daily",
        "nombre": "Healthcheck diario",
        "descripcion": "Job de verificación operativa del worker asíncrono.",
        "handler": "healthcheck",
        "intervalo_minutos": 1440,
        "activo": True,
    },
]


def seed_feature_flags_and_jobs(apps, schema_editor):
    FeatureFlag = apps.get_model("licencias", "FeatureFlag")
    ScheduledJob = apps.get_model("licencias", "ScheduledJob")
    now = django.utils.timezone.now()

    for payload in FEATURE_FLAGS_SEED:
        FeatureFlag.objects.update_or_create(
            codigo=payload["codigo"],
            defaults=payload,
        )

    for payload in SCHEDULED_JOBS_SEED:
        ScheduledJob.objects.update_or_create(
            codigo=payload["codigo"],
            defaults={**payload, "proxima_ejecucion": now},
        )


def unseed_feature_flags_and_jobs(apps, schema_editor):
    FeatureFlag = apps.get_model("licencias", "FeatureFlag")
    ScheduledJob = apps.get_model("licencias", "ScheduledJob")
    FeatureFlag.objects.filter(codigo__in=[item["codigo"] for item in FEATURE_FLAGS_SEED]).delete()
    ScheduledJob.objects.filter(codigo__in=[item["codigo"] for item in SCHEDULED_JOBS_SEED]).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('licencias', '0044_casointerno_rangos_fechas_adicionales_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('exitoso', 'Exitoso'), ('error', 'Error'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('prioridad', models.PositiveSmallIntegerField(db_index=True, default=100)),
                ('ejecutar_despues_de', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('max_intentos', models.PositiveSmallIntegerField(default=3)),
                ('locked_by', models.CharField(blank=True, max_length=100)),
                ('locked_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job asíncrono',
                'verbose_name_plural': 'Jobs asíncronos',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('modulo', models.CharField(db_index=True, max_length=80)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Si está desactivado, nadie puede usar este módulo.', verbose_name='Habilitado globalmente')),
                ('habilitado_por_defecto', models.BooleanField(default=True, help_text='Valor por defecto para usuarios sin regla por grupo.', verbose_name='Habilitado por defecto')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature flag',
                'verbose_name_plural': 'Feature flags',
                'ordering': ('modulo', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('handler', models.CharField(help_text='Nombre del handler registrado en la infraestructura de jobs.', max_length=80, verbose_name='Handler del job')),
                ('intervalo_minutos', models.PositiveIntegerField(default=60)),
                ('activo', models.BooleanField(default=True)),
                ('proxima_ejecucion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('exitoso', 'Exitoso'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('ultimo_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job programado',
                'verbose_name_plural': 'Jobs programados',
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='DataQualityRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('programado', 'Programado'), ('cli', 'CLI')], default='manual', max_length=20)),
                ('estado', models.CharField(choices=[('ejecutando', 'Ejecutando'), ('exitoso', 'Exitoso'), ('error', 'Error')], default='ejecutando', max_length=20)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('async_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_runs', to='licencias.asyncjob')),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridas_calidad_datos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corrida de calidad de datos',
                'verbose_name_plural': 'Corridas de calidad de datos',
                'ordering': ('-iniciado_en',),
            },
        ),
        migrations.CreateModel(
            name='BitacoraCambioCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(db_index=True, max_length=50)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('eliminado', 'Eliminado'), ('cambio_estatus', 'Cambio de estatus'), ('ejecutado', 'Ejecutado'), ('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado'), ('error', 'Error')], db_index=True, max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('antes', models.JSONField(blank=True, default=dict)),
                ('despues', models.JSONField(blank=True, default=dict)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_cambios_criticos', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_cambios_criticos', to='licencias.casointerno')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacora_cambios_criticos', to='contenttypes.contenttype')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_cambios_criticos', to='licencias.licenciaregistro')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_cambios_criticos', to='licencias.tramitecaso')),
            ],
            options={
                'verbose_name': 'Bitácora de cambio crítico',
                'verbose_name_plural': 'Bitácora de cambios críticos',
                'ordering': ('-creado_en', '-id'),
            },
        ),
        migrations.AddField(
            model_name='asyncjob',
            name='scheduled_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_ejecutados', to='licencias.scheduledjob'),
        ),
        migrations.CreateModel(
            name='FeatureFlagGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_actualizados', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_grupo', to='licencias.featureflag')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='auth.group')),
            ],
            options={
                'verbose_name': 'Regla de feature flag por grupo',
                'verbose_name_plural': 'Reglas de feature flags por grupo',
                'ordering': ('flag__modulo', 'flag__codigo', 'grupo__name'),
                'unique_together': {('flag', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='EventoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('caso', 'Caso'), ('tramite', 'Trámite'), ('licencia', 'Licencia'), ('estatus', 'Estatus'), ('job', 'Job'), ('calidad_datos', 'Calidad de datos'), ('feature_flag', 'Feature flag'), ('sistema', 'Sistema')], db_index=True, max_length=30)),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('actualizado', 'Actualizado'), ('eliminado', 'Eliminado'), ('cambio_estatus', 'Cambio de estatus'), ('ejecutado', 'Ejecutado'), ('detectado', 'Detectado'), ('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado'), ('error', 'Error')], db_index=True, max_length=30)),
                ('descripcion', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_sistema', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_sistema', to='licencias.casointerno')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_sistema', to='contenttypes.contenttype')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_sistema', to='licencias.licenciaregistro')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_sistema', to='licencias.tramitecaso')),
            ],
            options={
                'verbose_name': 'Evento del sistema',
                'verbose_name_plural': 'Eventos del sistema',
                'ordering': ('-creado_en', '-id'),
                'indexes': [models.Index(fields=['categoria', 'accion', 'creado_en'], name='licencias_e_categor_02b207_idx'), models.Index(fields=['content_type', 'object_id'], name='licencias_e_content_b0beb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('incompleto', 'Expediente incompleto'), ('duplicado', 'Expediente duplicado'), ('inconsistente', 'Dato inconsistente')], db_index=True, max_length=20)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('regla_codigo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('entidad_tipo', models.CharField(choices=[('caso', 'Caso'), ('tramite', 'Trámite'), ('licencia', 'Licencia')], db_index=True, max_length=20)),
                ('entidad_id', models.PositiveIntegerField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('primer_detectado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_detectado_en', models.DateTimeField(auto_now=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='licencias.casointerno')),
                ('licencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='licencias.licenciaregistro')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issues', to='licencias.tramitecaso')),
                ('ultima_corrida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='licencias.dataqualityrun')),
            ],
            options={
                'verbose_name': 'Hallazgo de calidad de datos',
                'verbose_name_plural': 'Hallazgos de calidad de datos',
                'ordering': ('-ultimo_detectado_en', '-id'),
                'indexes': [models.Index(fields=['activo', 'categoria', 'severidad'], name='licencias_d_activo_b0f97b_idx'), models.Index(fields=['entidad_tipo', 'entidad_id'], name='licencias_d_entidad_1ad483_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dataqualityissue',
            constraint=models.UniqueConstraint(fields=('categoria', 'regla_codigo', 'entidad_tipo', 'entidad_id'), name='quality_issue_unica_por_regla'),
        ),
        migrations.AddIndex(
            model_name='bitacoracambiocritico',
            index=models.Index(fields=['modulo', 'accion', 'creado_en'], name='licencias_b_modulo_f146e8_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacoracambiocritico',
            index=models.Index(fields=['content_type', 'object_id'], name='licencias_b_content_b71218_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacoracambiocritico',
            index=models.Index(fields=['actor', 'creado_en'], name='licencias_b_actor_i_12034e_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjob',
            index=models.Index(fields=['estado', 'ejecutar_despues_de', 'prioridad'], name='licencias_a_estado_1cb8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='asyncjob',
            index=models.Index(fields=['job_type', 'estado'], name='licencias_a_job_typ_bd9a7f_idx'),
        ),
        migrations.RunPython(seed_feature_flags_and_jobs, unseed_feature_flags_and_jobs),
    ]
