# Generated by Django 4.2.28 on 2026-02-16 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licencias', '0045_asyncjob_featureflag_scheduledjob_dataqualityrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroGuardadoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('casos_listado', 'Listado de trámites'), ('cola_trabajo', 'Mi cola de trabajo')], db_index=True, default='casos_listado', max_length=40)),
                ('nombre', models.CharField(max_length=120)),
                ('query_string', models.TextField(blank=True, help_text='Parámetros GET serializados (sin URL base).')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_guardados_operacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro guardado por usuario',
                'verbose_name_plural': 'Filtros guardados por usuario',
                'ordering': ('alcance', 'nombre', 'id'),
                'indexes': [models.Index(fields=['usuario', 'alcance'], name='licencias_f_usuario_faf719_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='filtroguardadousuario',
            constraint=models.UniqueConstraint(fields=('usuario', 'alcance', 'nombre'), name='filtro_guardado_usuario_nombre_unico'),
        ),
    ]
