# Generated by Django 4.2.28 on 2026-02-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0046_filtroguardadousuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casointerno',
            name='checklist_documental',
            field=models.JSONField(blank=True, default=dict, verbose_name='Checklist documental'),
        ),
        migrations.AddField(
            model_name='historicalcasointerno',
            name='checklist_documental',
            field=models.JSONField(blank=True, default=dict, verbose_name='Checklist documental'),
        ),
        migrations.AddField(
            model_name='historicaltramitecaso',
            name='checklist_documental',
            field=models.JSONField(blank=True, default=dict, verbose_name='Checklist documental'),
        ),
        migrations.AddField(
            model_name='tramitecaso',
            name='checklist_documental',
            field=models.JSONField(blank=True, default=dict, verbose_name='Checklist documental'),
        ),
        migrations.CreateModel(
            name='PlantillaCapturaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('caso', 'Trámite principal'), ('tramite', 'Trámite asociado')], db_index=True, default='caso', max_length=20, verbose_name='Ámbito')),
                ('nombre', models.CharField(blank=True, help_text='Etiqueta opcional para identificar la configuración en operación.', max_length=120, verbose_name='Nombre de plantilla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('reglas_campos', models.JSONField(blank=True, default=dict, help_text='Define campos visibles/requeridos por estatus. Formato esperado: managed_fields, default_visible_fields, default_required_fields y status_rules.', verbose_name='Reglas de campos')),
                ('checklist_etapas', models.JSONField(blank=True, default=list, help_text='Lista de etapas con documentos. Cada documento puede marcarse como crítico para bloquear avance.', verbose_name='Checklist documental por etapas')),
                ('esta_activa', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_captura', to='licencias.tipoproceso', verbose_name='Tipo de trámite')),
            ],
            options={
                'verbose_name': 'Plantilla de captura guiada',
                'verbose_name_plural': 'Plantillas de captura guiada',
                'ordering': ('tipo_proceso__nombre', 'ambito', 'orden', 'id'),
                'indexes': [models.Index(fields=['ambito', 'esta_activa'], name='licencias_p_ambito_d1d3dd_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='plantillacapturatipo',
            constraint=models.UniqueConstraint(fields=('tipo_proceso', 'ambito'), name='plantilla_captura_tipo_ambito_unica'),
        ),
    ]
