# Generated by Django 4.2.28 on 2026-02-16 06:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


SLA_BASE_NAME = "SLA base automática"
SLA_BASE_DEFAULTS = {
    "nombre": SLA_BASE_NAME,
    "dias_objetivo": 10,
    "dias_alerta_amarilla": 2,
    "dias_escalamiento": 2,
    "peso_riesgo": 50,
    "esta_activa": True,
    "orden": 99,
}
SCHEDULED_JOB_SLA = {
    "codigo": "sla-alert-scan-15m",
    "nombre": "Escaneo SLA cada 15 minutos",
    "descripcion": "Calcula semáforo SLA y genera alertas/escalamientos in-app.",
    "handler": "sla_alert_scan",
    "intervalo_minutos": 15,
    "activo": True,
}


def seed_sla_defaults_and_schedule(apps, schema_editor):
    TipoProceso = apps.get_model("licencias", "TipoProceso")
    SLARegla = apps.get_model("licencias", "SLARegla")
    ScheduledJob = apps.get_model("licencias", "ScheduledJob")
    now = django.utils.timezone.now()

    tipo_ids = list(TipoProceso.objects.values_list("id", flat=True))
    for tipo_id in tipo_ids:
        SLARegla.objects.get_or_create(
            ambito="caso",
            tipo_proceso_id=tipo_id,
            estatus_caso=None,
            defaults={**SLA_BASE_DEFAULTS, "estatus_tramite": None},
        )
        SLARegla.objects.get_or_create(
            ambito="tramite",
            tipo_proceso_id=tipo_id,
            estatus_tramite=None,
            defaults={**SLA_BASE_DEFAULTS, "estatus_caso": None},
        )

    ScheduledJob.objects.update_or_create(
        codigo=SCHEDULED_JOB_SLA["codigo"],
        defaults={**SCHEDULED_JOB_SLA, "proxima_ejecucion": now},
    )


def unseed_sla_defaults_and_schedule(apps, schema_editor):
    SLARegla = apps.get_model("licencias", "SLARegla")
    ScheduledJob = apps.get_model("licencias", "ScheduledJob")

    SLARegla.objects.filter(
        nombre=SLA_BASE_NAME,
        estatus_caso__isnull=True,
        estatus_tramite__isnull=True,
    ).delete()
    ScheduledJob.objects.filter(codigo=SCHEDULED_JOB_SLA["codigo"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('licencias', '0047_casointerno_checklist_documental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandejanotificacion',
            name='evento',
            field=models.CharField(choices=[('caso_creado', 'Caso creado'), ('caso_actualizado', 'Caso actualizado'), ('caso_estatus', 'Estatus de caso actualizado'), ('caso_eliminado', 'Caso eliminado'), ('tramite_creado', 'Trámite asociado creado'), ('tramite_actualizado', 'Trámite asociado actualizado'), ('tramite_estatus', 'Estatus de trámite actualizado'), ('tramite_eliminado', 'Trámite asociado eliminado'), ('minuta_eliminada', 'Minuta eliminada'), ('sla_alerta', 'Alerta SLA'), ('sla_escalamiento', 'Escalamiento SLA'), ('registro_leido', 'Registro leído')], max_length=40),
        ),
        migrations.CreateModel(
            name='SLARegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Etiqueta opcional para operación.', max_length=160)),
                ('ambito', models.CharField(choices=[('caso', 'Caso'), ('tramite', 'Trámite')], db_index=True, max_length=20)),
                ('dias_objetivo', models.PositiveIntegerField(default=10, help_text='Días máximos para el vencimiento del SLA.', verbose_name='Días objetivo')),
                ('dias_alerta_amarilla', models.PositiveSmallIntegerField(default=2, help_text='Días previos al vencimiento para cambiar a amarillo.', verbose_name='Alerta amarilla (días)')),
                ('dias_escalamiento', models.PositiveSmallIntegerField(default=2, help_text='Días de atraso para escalar por regla.', verbose_name='Escalamiento (días vencido)')),
                ('peso_riesgo', models.PositiveSmallIntegerField(default=50, help_text='Ajuste base del cálculo de riesgo (1-100).', verbose_name='Peso base de riesgo')),
                ('esta_activa', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estatus_caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_reglas', to='licencias.estatuscaso', verbose_name='Estatus de caso')),
                ('estatus_tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_reglas', to='licencias.estatustramite', verbose_name='Estatus de trámite')),
                ('grupo_escalamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_reglas_escalamiento', to='auth.group', verbose_name='Rol de escalamiento')),
                ('tipo_proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_reglas', to='licencias.tipoproceso', verbose_name='Tipo de trámite')),
            ],
            options={
                'verbose_name': 'Regla SLA',
                'verbose_name_plural': 'Reglas SLA',
                'ordering': ('ambito', 'tipo_proceso__nombre', 'orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SLAAlertaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('amarilla', 'Alerta amarilla'), ('roja', 'Alerta roja'), ('escalamiento', 'Escalamiento')], db_index=True, max_length=20)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('dias_restantes', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('async_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_alertas_registradas', to='licencias.asyncjob')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_alertas', to='licencias.casointerno')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='licencias.slaregla')),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_alertas', to='licencias.tramitecaso')),
            ],
            options={
                'verbose_name': 'Registro de alerta SLA',
                'verbose_name_plural': 'Registros de alertas SLA',
                'ordering': ('-creado_en', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='slaregla',
            index=models.Index(fields=['ambito', 'tipo_proceso', 'esta_activa'], name='licencias_s_ambito_d674c8_idx'),
        ),
        migrations.AddIndex(
            model_name='slaregla',
            index=models.Index(fields=['ambito', 'estatus_caso', 'esta_activa'], name='licencias_s_ambito_78ebdc_idx'),
        ),
        migrations.AddIndex(
            model_name='slaregla',
            index=models.Index(fields=['ambito', 'estatus_tramite', 'esta_activa'], name='licencias_s_ambito_d3555e_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaregla',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ambito', 'caso'), ('estatus_tramite__isnull', True)), models.Q(('ambito', 'tramite'), ('estatus_caso__isnull', True)), _connector='OR'), name='sla_regla_estatus_segun_ambito'),
        ),
        migrations.AddConstraint(
            model_name='slaregla',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'caso'), ('estatus_caso__isnull', False)), fields=('ambito', 'tipo_proceso', 'estatus_caso'), name='sla_regla_caso_tipo_estatus_unica'),
        ),
        migrations.AddConstraint(
            model_name='slaregla',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'caso'), ('estatus_caso__isnull', True)), fields=('ambito', 'tipo_proceso'), name='sla_regla_caso_base_unica'),
        ),
        migrations.AddConstraint(
            model_name='slaregla',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'tramite'), ('estatus_tramite__isnull', False)), fields=('ambito', 'tipo_proceso', 'estatus_tramite'), name='sla_regla_tramite_tipo_estatus_unica'),
        ),
        migrations.AddConstraint(
            model_name='slaregla',
            constraint=models.UniqueConstraint(condition=models.Q(('ambito', 'tramite'), ('estatus_tramite__isnull', True)), fields=('ambito', 'tipo_proceso'), name='sla_regla_tramite_base_unica'),
        ),
        migrations.AddIndex(
            model_name='slaalertaregistro',
            index=models.Index(fields=['tipo_alerta', 'fecha_vencimiento'], name='licencias_s_tipo_al_d55744_idx'),
        ),
        migrations.AddIndex(
            model_name='slaalertaregistro',
            index=models.Index(fields=['caso', 'creado_en'], name='licencias_s_caso_id_6eaec6_idx'),
        ),
        migrations.AddIndex(
            model_name='slaalertaregistro',
            index=models.Index(fields=['tramite', 'creado_en'], name='licencias_s_tramite_497362_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaalertaregistro',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('caso__isnull', False), ('tramite__isnull', True)), models.Q(('caso__isnull', True), ('tramite__isnull', False)), _connector='OR'), name='sla_alerta_un_objetivo'),
        ),
        migrations.AddConstraint(
            model_name='slaalertaregistro',
            constraint=models.UniqueConstraint(condition=models.Q(('caso__isnull', False), ('tramite__isnull', True)), fields=('caso', 'tipo_alerta', 'fecha_vencimiento'), name='sla_alerta_caso_unica'),
        ),
        migrations.AddConstraint(
            model_name='slaalertaregistro',
            constraint=models.UniqueConstraint(condition=models.Q(('caso__isnull', True), ('tramite__isnull', False)), fields=('tramite', 'tipo_alerta', 'fecha_vencimiento'), name='sla_alerta_tramite_unica'),
        ),
        migrations.RunPython(seed_sla_defaults_and_schedule, unseed_sla_defaults_and_schedule),
    ]
