# Generated by Django 4.2.28 on 2026-02-16 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licencias', '0048_alter_bandejanotificacion_evento_slaregla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandejanotificacion',
            name='evento',
            field=models.CharField(choices=[('caso_creado', 'Caso creado'), ('caso_actualizado', 'Caso actualizado'), ('caso_estatus', 'Estatus de caso actualizado'), ('caso_eliminado', 'Caso eliminado'), ('caso_mencion', 'Mención en comentario de caso'), ('caso_tarea_asignada', 'Tarea interna asignada'), ('caso_tarea_completada', 'Tarea interna completada'), ('tramite_creado', 'Trámite asociado creado'), ('tramite_actualizado', 'Trámite asociado actualizado'), ('tramite_estatus', 'Estatus de trámite actualizado'), ('tramite_eliminado', 'Trámite asociado eliminado'), ('minuta_eliminada', 'Minuta eliminada'), ('sla_alerta', 'Alerta SLA'), ('sla_escalamiento', 'Escalamiento SLA'), ('registro_leido', 'Registro leído')], max_length=40),
        ),
        migrations.CreateModel(
            name='CasoTareaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Tarea / acuerdo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_compromiso', models.DateField(db_index=True, verbose_name='Fecha compromiso')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], db_index=True, default='pendiente', max_length=20)),
                ('completada_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de completado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_internas', to='licencias.casointerno', verbose_name='Caso')),
                ('completada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_internas_completadas', to=settings.AUTH_USER_MODEL, verbose_name='Completada por')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_internas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_internas_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Tarea interna de caso',
                'verbose_name_plural': 'Tareas internas de caso',
                'ordering': ('fecha_compromiso', '-creado_en'),
                'indexes': [models.Index(fields=['caso', 'estado', 'fecha_compromiso'], name='licencias_c_caso_id_22b8f7_idx'), models.Index(fields=['responsable', 'estado'], name='licencias_c_respons_04fd0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CasoComentarioInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_caso', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_internos', to='licencias.casointerno', verbose_name='Caso')),
                ('menciones', models.ManyToManyField(blank=True, related_name='comentarios_mencionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios mencionados')),
            ],
            options={
                'verbose_name': 'Comentario interno de caso',
                'verbose_name_plural': 'Comentarios internos de caso',
                'ordering': ('-creado_en', '-id'),
                'indexes': [models.Index(fields=['caso', 'creado_en'], name='licencias_c_caso_id_140402_idx')],
            },
        ),
    ]
