# Generated by Django 4.2.28 on 2026-02-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licencias', '0049_alter_bandejanotificacion_evento_casotareainterna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestatuscaso',
            name='fecha_estatus',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del estatus'),
        ),
        migrations.AddField(
            model_name='historialestatustramitecaso',
            name='fecha_estatus',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del estatus'),
        ),
    ]
