# Generated by Django 4.2.25 on 2026-02-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0050_historialestatuscaso_fecha_estatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="casointerno",
            name="request_uid",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Identificador de envío",
            ),
        ),
        migrations.AddField(
            model_name="historicalcasointerno",
            name="request_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=64,
                null=True,
                verbose_name="Identificador de envío",
            ),
        ),
    ]
